import { describe, expect, it } from 'vitest';
import { decipherFplayUrl } from '../../src/platforms/doubao.js';

describe('Doubao FPLAY decryption', () => {
  it('matches the fixed byte vector generated by the Python baseline', () => {
    const seed = 'bm9kZS10cy1maXhlZC1zZWVk';
    const encrypted = 'RlBMWSHfF6ejgFv9r0nlwhQ56bp9iBTEhGCk5ipY0TDQ8PsfsBoAm3p45YuRbvAVl-FPr2isEhOF2EbJkai83A1y0Ug';
    expect(decipherFplayUrl(encrypted, seed))
      .toBe('https://media.example.com/original.mp4?token=fixed');
  });

  it('does not expose partial plaintext for invalid input', () => {
    expect(decipherFplayUrl('invalid', 'invalid')).toBe('');
  });
});
